# Generated by Django 5.1.4 on 2024-12-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='질문')),
                ('response', models.TextField(verbose_name='응답')),
                ('sources', models.JSONField(verbose_name='출처')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '질의',
                'verbose_name_plural': '질의들',
                'ordering': ['-created_at'],
            },
        ),
    ]
